name: 'Terraform Apply on push'
on:
  push:
    branches:
      - main
#    paths:
#      - 'infrastructure/aws/**'
env:
  tf_version: '1.1.6'
  tf_working_dir: 'infrastructure/aws'
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#  TF_VAR_certificate-arn: ${{ secrets.CERTIFICATE_ARN }}
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
